apiVersion: v1
kind: Service
metadata:
  name: swaggerui-service
  labels:
    tier: dynamicmicroservice
spec:
  type: ClusterIP
  selector:
    app: swaggerui-app
  ports:
    - port: 80
      targetPort: 80
